WebApplication1/WebApplication1/Controllers/AdminController.cs
using BigFamilyWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace BigFamilyWeb.Controllers
{
    public class AdminController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        // GET: Admin
        [HttpPost]
        public ActionResult Index(LoginModel model)
        {
            if (model.Username != null && model.Password != null)
            {
                var log = model.Username;
                var pass = model.Password;

                if (System.Configuration.ConfigurationManager.AppSettings["AdminLogin"] == log &&
                    System.Configuration.ConfigurationManager.AppSettings["AdminPassword"] == pass)
                {
                    FormsAuthentication.RedirectFromLoginPage(log, false);
                }
            }
            return View();
        }
        
        public ActionResult Dashboard()
        {
            return View();
        }
    }
}

WebApplication1/WebApplication1/Controllers/EmailsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BigFamilyWeb;

namespace BigFamilyWeb.Controllers
{
    public class EmailsController : Controller
    {
        private familydbEntities db = new familydbEntities();

        // GET: Emails
        public ActionResult Index()
        {
            return View(db.Emails.ToList());
        }

        // GET: Emails/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Email email = db.Emails.Find(id);
            if (email == null)
            {
                return HttpNotFound();
            }
            return View(email);
        }

        // GET: Emails/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Emails/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Email1,Id")] Email email)
        {
            if (ModelState.IsValid)
            {
                db.Emails.Add(email);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(email);
        }

        // GET: Emails/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Email email = db.Emails.Find(id);
            if (email == null)
            {
                return HttpNotFound();
            }
            return View(email);
        }

        // POST: Emails/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Email1,Id")] Email email)
        {
            if (ModelState.IsValid)
            {
                db.Entry(email).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(email);
        }

        // GET: Emails/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Email email = db.Emails.Find(id);
            if (email == null)
            {
                return HttpNotFound();
            }
            return View(email);
        }

        // POST: Emails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Email email = db.Emails.Find(id);
            db.Emails.Remove(email);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/WebApplication1/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BigFamilyWeb;

namespace BigFamilyWeb.Controllers
{
    public class NewsController : Controller
    {
        private familydbEntities db = new familydbEntities();

        // GET: News
        public ActionResult Index()
        {
            return View(db.News.ToList());
        }

        // GET: News/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.News.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // GET: News/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: News/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "NewsId,Title,Content,ImageURL,InsertDate")] News news, HttpPostedFileBase ImageUpload)
        {
            string filename = "";
            if (ImageUpload != null)
            {
                if (System.IO.File.Exists(Server.MapPath("~/" + news.ImageURL)))
                    System.IO.File.Delete(Server.MapPath("~/" + news.ImageURL));
                // получаем имя файла
                filename = System.IO.Path.GetFileName(ImageUpload.FileName);
                // сохраняем файл в папку Files в проекте
                ImageUpload.SaveAs(System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath + "Content\\news\\" + filename);
                news.ImageURL = "/Content/news/" + filename;
            }
            news.InsertDate = DateTime.Now;
            news.ImageURL = "/Content/news/" + filename;
            if (ModelState.IsValid)
            {
                news.InsertDate = DateTime.Now;
                db.News.Add(news);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(news);
        }

        // GET: News/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.News.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // POST: News/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "NewsId,Title,Content,ImageURL,InsertDate")] News news, HttpPostedFileBase ImageUpload)
        {
            string filename = "";
            if (ImageUpload != null)
            {
                if (System.IO.File.Exists(Server.MapPath("~/" + news.ImageURL)))
                    System.IO.File.Delete(Server.MapPath("~/" + news.ImageURL));
                // получаем имя файла
                filename = System.IO.Path.GetFileName(ImageUpload.FileName);
                // сохраняем файл в папку Files в проекте
                ImageUpload.SaveAs(System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath + "Content\\news\\" + filename);
                news.ImageURL = "/Content/news/" + filename;
            }
            news.InsertDate = DateTime.Now;

            news.ImageURL = "/Content/news/" + filename;
            if (ModelState.IsValid)
            {
                db.Entry(news).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(news);
        }

        // GET: News/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.News.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // POST: News/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            News news = db.News.Find(id);
            if (System.IO.File.Exists(Server.MapPath("~/" + news.ImageURL)))
                System.IO.File.Delete(Server.MapPath("~/" + news.ImageURL));
            db.News.Remove(news);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/WebApplication1/Controllers/PhonesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BigFamilyWeb;

namespace BigFamilyWeb.Controllers
{
    public class PhonesController : Controller
    {
        private familydbEntities db = new familydbEntities();

        // GET: Phones
        public ActionResult Index()
        {
            return View(db.Phones.ToList());
        }

        // GET: Phones/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Phone phone = db.Phones.Find(id);
            if (phone == null)
            {
                return HttpNotFound();
            }
            return View(phone);
        }

        // GET: Phones/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Phones/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Phone1,Id")] Phone phone)
        {
            if (ModelState.IsValid)
            {
                db.Phones.Add(phone);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(phone);
        }

        // GET: Phones/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Phone phone = db.Phones.Find(id);
            if (phone == null)
            {
                return HttpNotFound();
            }
            return View(phone);
        }

        // POST: Phones/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Phone1,Id")] Phone phone)
        {
            if (ModelState.IsValid)
            {
                db.Entry(phone).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(phone);
        }

        // GET: Phones/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Phone phone = db.Phones.Find(id);
            if (phone == null)
            {
                return HttpNotFound();
            }
            return View(phone);
        }

        // POST: Phones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Phone phone = db.Phones.Find(id);
            db.Phones.Remove(phone);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/WebApplication1/Views/Shared/Admin_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Управлние</title>
    @Styles.Render("~/Content/bootstrap_css")
    @Styles.Render("~/Content/admin_css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container" >
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Панель управления Big Family", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("На сайт", "Index", "Home")</li>
                    <li>@Html.ActionLink("Управление", "Dashboard", "Admin")</li>
                    <li>@Html.ActionLink("Новости", "Index", "News")</li>
                    <li>@Html.ActionLink("Сектора", "Index", "Sectors")</li>
                    <li>@Html.ActionLink("Контакты", "Index", "Contacts")</li>
                    <li>@Html.ActionLink("Почтовые адреса", "Index", "Emails")</li>
                    <li>@Html.ActionLink("Телфоны", "Index", "Phones")</li>
                    <li>@Html.ActionLink("Партнеры", "Index", "Members")</li>
                </ul>
            </div>
        </div>
    </div>
    <div style="margin-top:100px;" class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication1/WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="Content/images/logo.png" type="image/png">
    <title>@ViewBag.Title</title>
    <meta name="description" content="@ViewBag.Meta" />
    @Styles.Render("~/Content/footer_css")
</head>
<body>
  
        @RenderBody()
        <footer>
            <div class="communications">
                <p>Быстрая связь</p>

                    @using (Ajax.BeginForm("Index", new AjaxOptions { UpdateTargetId = "results" }))
                    {
                        @Html.AntiForgeryToken()
                        <input type="text" name="FirstName" placeholder="Имя" class="min_input" required="true">
                        <input type="email" name="Email" placeholder="Электронная почта" class="min_input" required="true">

                        <textarea name="Adress2" id="" cols="30" rows="10" class="message" placeholder="Сообщение" required="true"></textarea>
                        <input type="submit" value="Отправить" class="comm_button">
                        <span id="results"></span>

                    }
            </div>
            <div id="contacts">
                <p class="cont_name">Контакты</p>
                <div>
                    <img src="/Content/images/phone.png" alt="phone">
                    <p>+38 (066) 355-84-12</p>
                </div>
                <div>
                    <img src="/Content/images/vk2.png" alt="vk">
                    <p><a href="https://vk.com/bigfamilyzp">https://vk.com/bigfamilyzp</a></p>
                </div>
                <div>
                    <img src="/Content/images/email.png" alt="email">
                    <p>bigfamilyzp@gmail.com</p>
                </div>

            </div>

            <div class="footer_menu">
                <p class="consultation">Консультация</p>
                <ul>
                    <li>
                        @Html.ActionLink("Главная", "Index", "Home")
                    </li>
                    <li>
                        @Html.ActionLink("О нас", "About", "Home")
                    </li>
                    <li>
                        @Html.ActionLink("Услуги", "Services", "Home")
                    </li>
                    <li>
                        @Html.ActionLink("Новости", "News", "Home")
                    </li>
                    <li>
                        @Html.ActionLink("Партнеры", "Partners", "Home")
                    </li>
                    <li class="click">
                        <a href="#contacts">Контакты</a>
                    </li>
                </ul>
            </div>
        </footer>

    
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/scripts")
    @RenderSection("scripts", required: false)
</body>
</html>