WebApplication1/WebApplication1/Controllers/SectorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BigFamilyWeb;
using System.Reflection;

namespace BigFamilyWeb.Controllers
{
    public class SectorsController : Controller
    {
        private familydbEntities db = new familydbEntities();
        private string Message;
        public ActionResult Error()
        {
            return View();
        }

        // GET: Sectors
        public ActionResult Index()
        {
            return View(db.Sectors.ToList());
        }

        // GET: Sectors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sector sector = db.Sectors.Find(id);
            if (sector == null)
            {
                return HttpNotFound();
            }
            return View(sector);
        }

        // GET: Sectors/Create
        public ActionResult Create()
        {
            return View();
        }

         void ProcessUpload(dynamic model, HttpPostedFileBase upload,string propertyName,string uploadFolder)
        {
            PropertyInfo UrlProperty = model.GetType().GetProperty(propertyName);

            if (System.IO.File.Exists(Server.MapPath("~/" + UrlProperty.GetValue(model))))
                    System.IO.File.Delete(Server.MapPath("~/" + UrlProperty.GetValue(model)));
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(upload.FileName);
            // сохраняем файл в папку Files в проекте
                upload.SaveAs(string.Format("{0}Content\\{1}\\{2}",System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath, uploadFolder,fileName));
            UrlProperty.SetValue(model, string.Format("/Content/{0}/{1}", uploadFolder,fileName));

        }

        // POST: Sectors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create([Bind(Include = "SectorId,Name,Description,ImageURL,ImaeMobileURL,PriceURL,MinImageUrl,MinTitle,LampColor,DecorationURL")] Sector sector, HttpPostedFileBase MinUpload, HttpPostedFileBase PriceUpload, HttpPostedFileBase ImageUpload, HttpPostedFileBase ImageMobileUpload, HttpPostedFileBase ImageDecorationUpload)
        {
            sector.Contacts = "AAAAAAAAAA";
            sector.MinKeywords = "BBBBBBBBBBB";
            sector.MinImageUrl = "CCCCCCCCCCC";
            if (MinUpload != null)
                ProcessUpload(sector, MinUpload, "MinImageUrl", "sectorMinImages");

            sector.DecorationURL = "";
            if (ImageDecorationUpload != null)
                ProcessUpload(sector, ImageDecorationUpload, "DecorationURL", "decorations");

            sector.PriceURL = "";
            if (PriceUpload != null)
                ProcessUpload(sector, PriceUpload, "PriceURL", "prices");

            sector.ImageURL = "";
            if (ImageUpload != null)
                ProcessUpload(sector, ImageUpload, "ImageURL", "sectorBigImages");
                
            sector.ImageMobileURL = "";
            if (ImageMobileUpload != null)
                ProcessUpload(sector, ImageMobileUpload, "ImageMobileURL", "sectorBigImages");
            
            if (ModelState.IsValid)
            {
                db.Sectors.Add(sector);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sector);
        }

        // GET: Sectors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sector sector = db.Sectors.Find(id);
            if (sector == null)
            {
                return HttpNotFound();
            }
            return View(sector);
        }

        // POST: Sectors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit([Bind(Include = "Name,Description,ImageURL,ImageMobileURL,SectorId,PriceURL,MinImageUrl,MinTitle,LampColor,DecorationURL")] Sector sector, HttpPostedFileBase MinUpload, HttpPostedFileBase PriceUpload, HttpPostedFileBase ImageUpload, HttpPostedFileBase ImageMobileUpload, HttpPostedFileBase ImageDecorationUpload)
        {
            sector.Contacts = "";
            sector.MinKeywords = "";
            if (MinUpload != null)
            {
                if (System.IO.File.Exists(Server.MapPath("~/" + sector.MinImageUrl)))
                    System.IO.File.Delete(Server.MapPath("~/" + sector.MinImageUrl));

                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(MinUpload.FileName);
                // сохраняем файл в папку Files в проекте
                MinUpload.SaveAs(System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath + "Content\\sectorMinImages\\" + fileName);
                sector.MinImageUrl = "/Content/sectorMinImages/" + fileName;
            }
            if (ImageDecorationUpload != null)
            {
                if (System.IO.File.Exists(Server.MapPath("~/" + sector.DecorationURL)))
                    System.IO.File.Delete(Server.MapPath("~/" + sector.DecorationURL));
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(ImageDecorationUpload.FileName);
                // сохраняем файл в папку Files в проекте
                ImageDecorationUpload.SaveAs(System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath + "Content\\decorations\\" + fileName);
                sector.DecorationURL = "/Content/decorations/" + fileName;
            }
            if (ImageUpload != null)
            {
                if (System.IO.File.Exists(Server.MapPath("~/" + sector.ImageURL)))
                    System.IO.File.Delete(Server.MapPath("~/" + sector.ImageURL));
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(ImageUpload.FileName);
                // сохраняем файл в папку Files в проекте
                ImageUpload.SaveAs(System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath + "Content\\sectorBigImages\\" + fileName);
                sector.ImageURL = "/Content/sectorBigImages/" + fileName;
            }
            if (ImageMobileUpload != null)
            {
                if (System.IO.File.Exists(Server.MapPath("~/" + sector.ImageMobileURL)))
                    System.IO.File.Delete(Server.MapPath("~/" + sector.ImageMobileURL));
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(ImageMobileUpload.FileName);
                // сохраняем файл в папку Files в проекте
                ImageMobileUpload.SaveAs(System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath + "Content\\sectorBigImages\\" + fileName);
                sector.ImageMobileURL = "/Content/sectorBigImages/" + fileName;
            }
            if (PriceUpload != null)
            {
                if (System.IO.File.Exists(Server.MapPath("~/" + sector.PriceURL)))
                    System.IO.File.Delete(Server.MapPath("~/" + sector.PriceURL));
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(PriceUpload.FileName);
                // сохраняем файл в папку Files в проекте
                PriceUpload.SaveAs(System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath + "Content\\prices\\" + fileName);
                sector.PriceURL = "/Content/prices/" + fileName;
            }
            if (ModelState.IsValid)
            {
                db.Entry(sector).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sector);
        }

        // GET: Sectors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sector sector = db.Sectors.Find(id);
            if (sector == null)
            {
                return HttpNotFound();
            }
            return View(sector);
        }

        // POST: Sectors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Sector sector = db.Sectors.Find(id);
            if (System.IO.File.Exists(Server.MapPath("~/" + sector.MinImageUrl)))
                System.IO.File.Delete(Server.MapPath("~/" + sector.MinImageUrl));
            if (System.IO.File.Exists(Server.MapPath("~/" + sector.ImageURL)))
                System.IO.File.Delete(Server.MapPath("~/" + sector.ImageURL));
            if (System.IO.File.Exists(Server.MapPath("~/" + sector.ImageMobileURL)))
                System.IO.File.Delete(Server.MapPath("~/" + sector.ImageMobileURL));
            if (System.IO.File.Exists(Server.MapPath("~/" + sector.PriceURL)))
                System.IO.File.Delete(Server.MapPath("~/" + sector.PriceURL));
            if (System.IO.File.Exists(Server.MapPath("~/" + sector.DecorationURL)))
                System.IO.File.Delete(Server.MapPath("~/" + sector.DecorationURL));
            db.Sectors.Remove(sector);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

WebApplication1/WebApplication1/Views/Sectors/Create.cshtml
@model BigFamilyWeb.Sector

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

<h2>Создать сектор</h2>

@using (Html.BeginForm("Create", "Sectors", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Сектор</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2" for="Name">Имя Сетора</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Description">Описание</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @cols = "30", @rows = "10" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="ImageURL">Фоновая картинка</label>
            <div class="col-md-10">
                <input type="file" name="ImageUpload" /><br>
                @Html.HiddenFor(model => model.ImageURL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="ImageMobileURL">Уменьшенная фоновая картинка</label>
            <div class="col-md-10">
                <input type="file" name="ImageMobileUpload" /><br>
                @Html.HiddenFor(model => model.ImageMobileURL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageMobileURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="DecorationURL">Картинка декорации</label>
            <div class="col-md-10">
                <input type="file" name="ImageDecorationUpload" /><br>
                @Html.HiddenFor(model => model.DecorationURL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DecorationURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="PriceURL">Ссылка на прайс</label>
            <div class="col-md-10">
                <input type="file" name="PriceUpload" /><br>
                @Html.HiddenFor(model => model.PriceURL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PriceURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="MinImageUrl">Картинка миниатюры (в сетке)</label>
            <div class="col-md-10">
                <input type="file" name="MinUpload" /><br>
                @Html.HiddenFor(model => model.MinImageUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MinImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="MinTitle">Минимальное описание (в сетке)</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.MinTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MinTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.MinKeywords, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MinKeywords, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MinKeywords, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            <label class="control-label col-md-2" for="LampColor">Цвет лампочки (green,yellow,red)</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.LampColor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LampColor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад к списку", "Index")
</div>

WebApplication1/WebApplication1/Views/Sectors/Delete.cshtml
@model BigFamilyWeb.Sector

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

<h2>Удалить сектор @Html.DisplayFor(model => model.Name)</h2>

<h3>Уверены что хотите удалить сектор @Html.DisplayFor(model => model.Name)?</h3>
<div>
    <h4>Sector</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageURL)
            <img src="@Model.ImageURL" width="100" height="100" />
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ImageMobileURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageMobileURL)
            <img src="@Model.ImageURL" width="100" height="100" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DecorationURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DecorationURL)
            <img src="@Model.DecorationURL" width="100" height="100" />
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Contacts)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contacts)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PriceURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PriceURL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MinImageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MinImageUrl)
            <img src="@Model.MinImageUrl" width="100" height="100" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MinTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MinTitle)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.MinKeywords)
        </dt>*@

        <dd>
            @Html.DisplayFor(model => model.MinKeywords)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LampColor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LampColor)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Назад к списку", "Index")
        </div>
    }
</div>

WebApplication1/WebApplication1/Views/Sectors/Details.cshtml
@model BigFamilyWeb.Sector

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

<h2>Детально @Html.DisplayFor(model => model.Name)</h2>

<div>
    <h4>Sector</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PriceURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PriceURL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageURL)
            <img src="@Model.ImageURL" width="100" height="100" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageMobileURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageMobileURL)
            <img src="@Model.ImageMobileURL" width="100" height="100" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DecorationURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DecorationURL)
            <img src="@Model.DecorationURL" width="100" height="100" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contacts)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contacts)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PriceURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PriceURL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MinImageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MinImageUrl)
            <img src="@Model.MinImageUrl" width="100" height="100" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MinTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MinTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MinKeywords)
        </dt>

        @*<dd>
            @Html.DisplayFor(model => model.MinKeywords)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.LampColor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LampColor)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Изменить", "Edit", new { id = Model.SectorId }) |
    @Html.ActionLink("Назад к списку", "Index")
</p>

WebApplication1/WebApplication1/Views/Sectors/Edit.cshtml
@model BigFamilyWeb.Sector

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

<h2>Редактирование</h2>

@using (Html.BeginForm("Edit", "Sectors", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Сектор @Html.DisplayFor(model => model.Name) </h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2" for="Name">Имя Сетора</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Description">Описание</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @cols = "30", @rows = "10" })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="ImageURL">Фоновая картинка</label>
            <div class="col-md-10">
                <input type="file" name="ImageUpload" /><br>
                @Html.HiddenFor(model => model.ImageURL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="ImageMobileURL">Уменьшенная фоновая картинка</label>
            <div class="col-md-10">
                <input type="file" name="ImageMobileUpload" /><br>
                @Html.HiddenFor(model => model.ImageMobileURL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageMobileURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="DecorationURL">Картинка декорации</label>
            <div class="col-md-10">
                <input type="file" name="ImageDecorationUpload" /><br>
                @Html.HiddenFor(model => model.DecorationURL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DecorationURL, "", new { @class = "text-danger" })
            </div>
        </div>


        @Html.HiddenFor(model => model.SectorId)

        <div class="form-group">
            <label class="control-label col-md-2" for="PriceURL">Ссылка на прайс</label>
            <div class="col-md-10">
                <input type="file" name="PriceUpload" /><br>
                @Html.HiddenFor(model => model.PriceURL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PriceURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="MinImageUrl">Картинка миниатюры (в сетке)</label>
            <div class="col-md-10">
                <input type="file" name="MinUpload" /><br>
                @Html.HiddenFor(model => model.MinImageUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MinImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="MinTitle">Минимальное описание (в сетке)</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.MinTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MinTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.MinKeywords, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MinKeywords, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MinKeywords, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <label class="control-label col-md-2" for="LampColor">Цвет лампочки (green,yellow,red)</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.LampColor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LampColor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
     </div>
}

<div>
    @Html.ActionLink("Назад к списку", "Index")
</div>

WebApplication1/WebApplication1/Views/Sectors/Index.cshtml
@model IEnumerable<BigFamilyWeb.Sector>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

<h2>Управление секторами</h2>

<p>
    @Html.ActionLink("Создать сектор", "Create")
</p>
<table class="table">
    <tr>
        <th></th>
        <th>
            Описание
        </th>
        <th>
            Имя Сектора
        </th>
        
        <th>
            Минимальное описание(название в сетке)
        </th>
        <th>
            Цвет лампочки (green,yellow,red)
        </th>
        
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink("Изменить", "Edit", new { id = item.SectorId }) |
            @Html.ActionLink("Детельнее", "Details", new { id = item.SectorId }) |
            @Html.ActionLink("Удалить", "Delete", new { id = item.SectorId })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.MinTitle)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.MinKeywords)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.LampColor)
        </td>
        
    </tr>
}

</table>