WebApplication1/WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace BigFamilyWeb.Controllers
{
    public class HomeController : Controller
    {
        private familydbEntities db = new familydbEntities();
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(Contact contact)
        {
            contact.Adress1 = "Не указано";
            contact.Company = "Не указано";
            contact.IsNew = true;
            contact.LastName = "Не указано";
            contact.Phone1 = "Не указано";
            contact.Phone2 = "Не указано";
            contact.Surname = "Не указано";
            if (ModelState.IsValid)
            {
                SmtpClient smtp = new SmtpClient("smtp.gmail.com", 587);
                smtp.UseDefaultCredentials = false;
                smtp.Credentials = new NetworkCredential("Bigfamilyzp@gmail.com", "halepa159753");
                smtp.EnableSsl = true;

                MailMessage emailMes = new MailMessage("Bigfamilyzp@gmail.com", "Halepaas@gmail.com", "Новый контакт --> BigFamily", "BigFamily: Новый запрос в контактах!\n\n " + contact.FirstName+ " \n" +contact.Email+ "\n Сообщение: " + contact.Adress2);
                smtp.Send(emailMes);

                db.Contacts.Add(contact);
                db.SaveChanges();
                return PartialView("SendStatus", "Отправлено!");
            }
            return PartialView("SendStatus", "Не отправлено!");
        }
    public ActionResult About()
        {
            return View();
        }
        public ActionResult Services()
        {
            return View(db.Sectors.ToList());
        }

        public ActionResult Sector(int id)
        {
            List<Sector> tempList = null;
            if (db.Sectors.Count() != 0)
                tempList = db.Sectors.ToList();
            
                if (id >= tempList.Count)
                    id = 0;
                if (id < 0)
                    id = tempList.Count - 1;

                ViewBag.SectorIndex = id;
            return View(tempList[id]);

        }
        public ActionResult News()
        {
            return View(db.News.ToList());
        }
        public ActionResult Partners()
        {
            return View(db.Members.ToList());
        }
        public ActionResult Phone()
        {
            return View(new Phone() {  Id=1, Phone1="2"});
        }
        public ActionResult Email()
        {
            return View(new Email() { Id = 1,Email1="fa@cd.com" });
        }

    }
}

WebApplication1/WebApplication1/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BigFamilyWeb;

namespace BigFamilyWeb.Controllers
{
    public class MembersController : Controller
    {
        private familydbEntities db = new familydbEntities();

        // GET: Members
        public ActionResult Index()
        {
            return View(db.Members.ToList());
        }

        // GET: Members/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // GET: Members/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Members/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MemberId,Description,ImageURL,Title")] Member member, HttpPostedFileBase ImageUpload)
        {
            if (ImageUpload != null)
            {
                if (System.IO.File.Exists(Server.MapPath("~/" + member.ImageURL)))
                    System.IO.File.Delete(Server.MapPath("~/" + member.ImageURL));
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(ImageUpload.FileName);
                // сохраняем файл в папку Files в проекте
                ImageUpload.SaveAs(System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath + "Content\\partnersImages\\" + fileName);
                member.ImageURL = "/Content/partnersImages/" + fileName;
            }
            else
            {
                member.ImageURL = "/Content/partnersImages/";
            }
            if (ModelState.IsValid)
            {
                db.Members.Add(member);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(member);
        }

        // GET: Members/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // POST: Members/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MemberId,Description,ImageURL,Title")] Member member, HttpPostedFileBase ImageUpload)
        {
            if (ImageUpload != null)
            {
                if (System.IO.File.Exists(Server.MapPath("~/" + member.ImageURL)))
                    System.IO.File.Delete(Server.MapPath("~/" + member.ImageURL));
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(ImageUpload.FileName);
                // сохраняем файл в папку Files в проекте
                ImageUpload.SaveAs(System.Web.Hosting.HostingEnvironment.ApplicationPhysicalPath + "Content\\partnersImages\\" + fileName);
                member.ImageURL = "/Content/partnersImages/" + fileName;
            }

            if (ModelState.IsValid)
            {
                db.Entry(member).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(member);
        }

        // GET: Members/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Member member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // POST: Members/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Member member = db.Members.Find(id);
            db.Members.Remove(member);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/WebApplication1/Views/Home/Members/Create.cshtml
@model BigFamilyWeb.Member

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Members", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Member</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-daFnger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ImageURL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageUpload" /><br>
                @Html.HiddenFor(model => model.ImageURL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад к списку", "Index")
</div>

WebApplication1/WebApplication1/Views/Home/Members/Delete.cshtml
@model BigFamilyWeb.Member

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Уверены что хотите удалить?</h3>
<div>
    <h4>Партнер</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageURL)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication1/WebApplication1/Views/Home/Members/Details.cshtml
@model BigFamilyWeb.Member

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Партнер</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageURL)
            <img src="@Html.DisplayFor(model => model.ImageURL)" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Изменить", "Edit", new { id = Model.MemberId }) |
    @Html.ActionLink("Назад к списку", "Index")
</p>

WebApplication1/WebApplication1/Views/Home/Members/Edit.cshtml
@model BigFamilyWeb.Member

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Members", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Партнер</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MemberId)

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ImageURL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageUpload" /><br>
                @Html.HiddenFor(model => model.ImageURL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageURL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад к списку", "Index")
</div>

WebApplication1/WebApplication1/Views/Home/Members/Index.cshtml
@model IEnumerable<BigFamilyWeb.Member>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Admin_Layout.cshtml";
}

<h2>Управление партнерами</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Ссылка на партнера
        </th>
        <th>
            Краткое описание партнера
        </th>
        <th>
            Адресс картинки
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ImageURL)
        </td>
        <td>
            @Html.ActionLink("Изменить", "Edit", new { id=item.MemberId }) |
            @Html.ActionLink("Детальнее", "Details", new { id=item.MemberId }) |
            @Html.ActionLink("Удалить", "Delete", new { id=item.MemberId })
        </td>
    </tr>
}

</table>